module.exports = {
    AWS_ACCESS_KEY_ID_NODE: process.env.AWS_ACCESS_KEY_ID_NODE,
    AWS_SECRET_ACCESS_KEY_NODE: process.env.AWS_SECRET_ACCESS_KEY_NODE,
    AWS_REGION: process.env.AWS_REGION_NODE,
    AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
    AWS_BUCKET_DONE_NAME: process.env.AWS_BUCKET_DONE_NAME,
    AWS_ACCOUNT_ID: process.env.AWS_ACCOUNT_ID,
};